import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Form from '../components/Form'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [controllerType,setControllerType] = useState<String>("get") 
  const navlinks: String[] = [
    "get","post","patch","update","delete","middleware"
  ]
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-[800px] my-10 mx-auto'>
        
        <h2 className='text-3xl font-semibold  '>Create your controller</h2>
        <Navbar navlinks={navlinks} controllerType = {controllerType} setControllerType = {setControllerType} />
        <Form Type = {controllerType} />
        {/* <h1 clas
        <Form /> */}
      </main>
        
    </div>
  )
}
